from pathlib import Path
path = Path('index.html')
text = path.read_text(encoding='utf-8')
old = "            const deliveryFee = 15000;\n            const foodTotal = total;\n            const promoCode = document.getElementById('promo-input').value.trim().toUpperCase();\n            const promoResult = validatePromoCode(promoCode);\n            const discount = calculateDiscount(foodTotal, promoResult);\n            const finalTotal = foodTotal > 0 ? foodTotal + deliveryFee - discount : 0;\n\n            let discountHTML = '';\n            if (promoResult.valid && discount > 0) {\n                discountHTML = `<p class=\"text-[11px] text-green-500 font-bold uppercase mb-1\">? Chegirma: -${discount.toLocaleString()} so'm</p>`;\n            }\n\n            document.getElementById('cart-total').innerHTML = `<div class=\"text-right\">\n                <p class=\"text-[10px] text-gray-500 font-bold uppercase mb-1\">${S.food_label}: ${foodTotal.toLocaleString()} so'm</p>\n                <p class=\"text-[10px] text-amber-600 dark:text-amber-400 font-bold uppercase mb-1\">${S.deliv_label}: ${deliveryFee.toLocaleString()} so'm</p>\n                ${discountHTML}\n                <p class=\"text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-red-600 to-red-500 mt-2\">${finalTotal.toLocaleString()} so'm</p>\n            </div>`;\n        }"
new = "            const deliveryFee = total >= DELIVERY_THRESHOLD ? 0 : BASE_DELIVERY_FEE;\n            const foodTotal = total;\n            const promoCode = document.getElementById('promo-input').value.trim().toUpperCase();\n            const promoResult = validatePromoCode(promoCode);\n            const discount = calculateDiscount(foodTotal, promoResult);\n            const finalTotal = foodTotal > 0 ? foodTotal + deliveryFee - discount : 0;\n\n            const deliveryMessage = total >= DELIVERY_THRESHOLD ? S.delivery_free : S.delivery_fee_note;\n\n            let discountHTML = '';\n            if (promoResult.valid && discount > 0) {\n                discountHTML = `<p class=\"text-[11px] text-emerald-500 font-bold uppercase mb-1\">? Chegirma: -${discount.toLocaleString()} so'm</p>`;\n            }\n\n            document.getElementById('cart-total').innerHTML = `<div class=\"text-right\">\n                <p class=\"text-[10px] text-gray-500 font-bold uppercase mb-1\">${S.food_label}: ${foodTotal.toLocaleString()} so'm</p>\n                <p class=\"text-[10px] text-amber-600 dark:text-amber-400 font-bold uppercase mb-1\">${S.deliv_label}: ${deliveryFee.toLocaleString()} so'm</p>\n                ${discountHTML}\n                <p class=\"text-3xl font-black text-transparent bg-clip-text bg-gradient-to-r from-red-600 to-red-500 mt-2\">${finalTotal.toLocaleString()} so'm</p>\n                <p class=\"text-[10px] font-bold uppercase tracking-widest mt-2 ${total >= DELIVERY_THRESHOLD ? 'text-emerald-500' : 'text-amber-400'}\">${deliveryMessage}</p>\n            </div>`;\n        }"
if old not in text:
    raise SystemExit('render block not found')
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
print('render block updated')
