from pathlib import Path
path = Path('index.html')
text = path.read_text(encoding='utf-8')
old = "        document.getElementById('checkout-btn').onclick = () => {\n            const total = cart.reduce((sum, i) => sum + (i.price * i.quantity), 0);\n            const promoCode = document.getElementById('promo-input').value.trim().toUpperCase();\n            const promoResult = validatePromoCode(promoCode);\n            const discount = calculateDiscount(total, promoResult);\n            const deliveryFee = 15000;\n            const finalTotal = total > 0 ? total + deliveryFee - discount : 0;\n\n            // Show promo validation dialog if code entered\n            if (promoCode && !promoResult.valid) {\n                alert('? Noto\'g\'ri promo kod!');\n                return;\n            }\n\n            // Show confirmation with promo details\n            let confirmMsg = `?? Buyurtma tasdiqlash:\n\n`;\n            confirmMsg += `?? Taomlar: ${total.toLocaleString()} so'm\n`;\n            confirmMsg += `?? Yetkazish: ${deliveryFee.toLocaleString()} so'm\n`;\n            if (promoResult.valid && discount > 0) {\n                confirmMsg += `? Chegirma: -${discount.toLocaleString()} so'm\n`;\n            }\n            confirmMsg += `\n?? Jami: ${finalTotal.toLocaleString()} so'm`;\n        }"
new = """        document.getElementById('checkout-btn').onclick = () => {\n            const total = cart.reduce((sum, i) => sum + (i.price * i.quantity), 0);\n            const promoCode = document.getElementById('promo-input').value.trim().toUpperCase();\n            const promoResult = validatePromoCode(promoCode);\n            const discount = calculateDiscount(total, promoResult);\n            const deliveryFee = total >= DELIVERY_THRESHOLD ? 0 : BASE_DELIVERY_FEE;\n            const finalTotal = total > 0 ? total + deliveryFee - discount : 0;\n            const deliveryMessage = total >= DELIVERY_THRESHOLD ? S.delivery_free : S.delivery_fee_note;\n\n            // Show promo validation dialog if code entered\n            if (promoCode && !promoResult.valid) {\n                alert('? Noto\'g\'ri promo kod!');\n                return;\n            }\n\n            // Show confirmation with promo details\n            let confirmMsg = `?? Buyurtma tasdiqlash:\n\n`;\n            confirmMsg += `?? Taomlar: ${total.toLocaleString()} so'm\n`;\n            confirmMsg += `?? Yetkazish: ${deliveryFee.toLocaleString()} so'm\n`;\n            if (promoResult.valid && discount > 0) {\n                confirmMsg += `? Chegirma: -${discount.toLocaleString()} so'm\n`;\n            }\n            if (deliveryMessage) {\n                confirmMsg += `?? ${deliveryMessage}\n`;\n            }\n            confirmMsg += `\n?? Jami: ${finalTotal.toLocaleString()} so'm`;\n        }"""
if old not in text:
    raise SystemExit('checkout block not found')
text = text.replace(old, new, 1)
path.write_text(text, encoding='utf-8')
print('checkout block replaced')
